# Generated by Django 5.2.17 on 2026-09-28 08:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Place',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('coordinates', models.JSONField()),
                ('category', models.CharField(max_length=100)),
                ('difficulty', models.CharField(blank=True, choices=[('EASY', 'Easy'), ('MODERATE', 'Moderate'), ('HARD', 'Hard')], max_length=20)),
                ('distance', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('estimated_duration', models.CharField(blank=True, max_length=100)),
                ('facilities', models.JSONField(blank=True, default=list)),
                ('safety_notes', models.TextField(blank=True)),
                ('images', models.JSONField(blank=True, default=list)),
                ('rating', models.DecimalField(decimal_places=2, default=0, max_digits=3)),
                ('is_verified', models.BooleanField(default=False)),
            ],
        ),
    ]
