# Generated by Django 5.2.17 on 2026-09-30 08:38

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('places', '0001_initial'),
        ('trails', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('category', models.CharField(choices=[('HIKE', 'Hike'), ('TRAIL_RUN', 'Trail run'), ('CYCLING', 'Cycling'), ('CAMPING', 'Camping'), ('MEETUP', 'Meetup'), ('CLEANUP_DRIVE', 'Cleanup drive')], max_length=20)),
                ('location', models.CharField(max_length=255)),
                ('meeting_point', models.CharField(blank=True, max_length=255)),
                ('start_at', models.DateTimeField()),
                ('end_at', models.DateTimeField(blank=True, null=True)),
                ('capacity', models.PositiveIntegerField()),
                ('difficulty', models.CharField(blank=True, choices=[('EASY', 'Easy'), ('MODERATE', 'Moderate'), ('HARD', 'Hard')], max_length=10)),
                ('requires_approval', models.BooleanField(default=False)),
                ('visibility', models.CharField(choices=[('PUBLIC', 'Public'), ('FOLLOWERS', 'Followers only'), ('INVITED', 'Only invited')], default='PUBLIC', max_length=15)),
                ('approval_status', models.CharField(choices=[('PENDING', 'Pending'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected')], default='PENDING', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('organizer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='organized_events', to=settings.AUTH_USER_MODEL)),
                ('place', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='events', to='places.place')),
                ('trail', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='events', to='trails.trail')),
            ],
            options={
                'ordering': ['start_at'],
            },
        ),
        migrations.CreateModel(
            name='EventParticipant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('PENDING', 'Pending approval'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected')], default='APPROVED', max_length=10)),
                ('joined_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='participants', to='events.event')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='event_participations', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['joined_at'],
            },
        ),
        migrations.AddIndex(
            model_name='event',
            index=models.Index(fields=['start_at'], name='events_even_start_a_268ef9_idx'),
        ),
        migrations.AddIndex(
            model_name='event',
            index=models.Index(fields=['visibility', 'approval_status'], name='events_even_visibil_cdbd97_idx'),
        ),
        migrations.AddIndex(
            model_name='event',
            index=models.Index(fields=['organizer', 'start_at'], name='events_even_organiz_fac916_idx'),
        ),
        migrations.AddIndex(
            model_name='eventparticipant',
            index=models.Index(fields=['event', 'status'], name='events_even_event_i_919975_idx'),
        ),
        migrations.AddIndex(
            model_name='eventparticipant',
            index=models.Index(fields=['user', 'status'], name='events_even_user_id_7d2361_idx'),
        ),
        migrations.AddConstraint(
            model_name='eventparticipant',
            constraint=models.UniqueConstraint(fields=('event', 'user'), name='unique_event_participant'),
        ),
    ]
