# Generated by Django 5.2.17 on 2026-09-28 09:55

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activities', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameField(
            model_name='activity',
            old_name='name',
            new_name='title',
        ),
        migrations.AddField(
            model_name='activity',
            name='activity_type',
            field=models.CharField(choices=[('HIKE', 'Hike'), ('TRAIL_RUN', 'Trail Run'), ('CYCLING', 'Cycling'), ('CAMPING', 'Camping'), ('MEETUP', 'Meetup')], default='HIKE', max_length=20),
        ),
        migrations.AddField(
            model_name='activity',
            name='difficulty',
            field=models.CharField(blank=True, choices=[('EASY', 'Easy'), ('MODERATE', 'Moderate'), ('HARD', 'Hard')], max_length=20),
        ),
        migrations.AddField(
            model_name='activity',
            name='distance',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='activity',
            name='duration',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='activity',
            name='end_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='activity',
            name='location',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='activity',
            name='notes',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='activity',
            name='place_id',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='activity',
            name='privacy',
            field=models.CharField(choices=[('PUBLIC', 'Public'), ('FOLLOWERS', 'Followers'), ('PRIVATE', 'Private')], default='PUBLIC', max_length=20),
        ),
        migrations.AddField(
            model_name='activity',
            name='start_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='activity',
            name='status',
            field=models.CharField(choices=[('PLANNED', 'Planned'), ('COMPLETED', 'Completed')], default='PLANNED', max_length=20),
        ),
        migrations.AddField(
            model_name='activity',
            name='trail_id',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddIndex(
            model_name='activity',
            index=models.Index(fields=['activity_type'], name='activities__activit_8e7970_idx'),
        ),
        migrations.AddIndex(
            model_name='activity',
            index=models.Index(fields=['start_at'], name='activities__start_a_023a7c_idx'),
        ),
    ]
