# Generated by Django 5.2.17 on 2026-09-28 08:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Trail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('location', models.CharField(max_length=200)),
                ('difficulty', models.CharField(blank=True, choices=[('EASY', 'Easy'), ('MODERATE', 'Moderate'), ('HARD', 'Hard')], max_length=20)),
                ('distance', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('estimated_duration', models.CharField(blank=True, max_length=100)),
                ('facilities', models.JSONField(blank=True, default=list)),
                ('safety_notes', models.TextField(blank=True)),
                ('images', models.JSONField(blank=True, default=list)),
                ('rating', models.DecimalField(decimal_places=2, default=0, max_digits=3)),
                ('is_verified', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['created_at'], name='trails_trai_created_93e9fc_idx'), models.Index(fields=['difficulty'], name='trails_trai_difficu_ccc0ef_idx')],
            },
        ),
        migrations.CreateModel(
            name='TrailPoint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('latitude', models.DecimalField(decimal_places=7, max_digits=10)),
                ('longitude', models.DecimalField(decimal_places=7, max_digits=10)),
                ('sequence', models.PositiveIntegerField()),
                ('trail', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='points', to='trails.trail')),
            ],
            options={
                'ordering': ['sequence'],
                'constraints': [models.UniqueConstraint(fields=('trail', 'sequence'), name='unique_trail_point_sequence')],
            },
        ),
    ]
